public with sharing class Errors 
{
    public static String objParmNotAvailStr = 'Obj parameter not found in URL.';
    public static String objNotAvailStr = ' object not found. Please check object\'s API name.' ;
    public static String noObjInCustomSettingStr = 'Object Name not found in search result view custom setting. Please create a record in custom setting for object : ';
    public static String noFildListInCusSetStr = 'Custom setting not having list of fields which need to be displayed in search result.' ;
}