// Copyright (c) 2012, 2013 All Rights Reserved
//
// This source is subject to the BigKite License granted to Skin Vitality, and only Skin Vitality.
// All code is owned solely by BigKite and BigKite hereby grants
// Skin Vitality a worldwide, perpetual, non-exclusive, non-transferable, royalty-free license to use and
// modify such work product solely for its internal business purposes.
// All other rights reserved.

public class resourceClass { 
    public Resource__c u {get; set; } 
    public string classname {get; set; } 
    public string backgroundcolor { get; set; } 
    public string color { get; set; }
    public  resourceClass(){
    }
}